micronaut:
  application:
    name: spoutbreezeInteractor
  session:
    http.cookie: true
    http.header: true
    http:
      redis:
        enabled: true

mongodb:
  uri: mongodb://${MONGO_HOST:localhost}:${MONGO_PORT:27017}
  
redis:
  uri: redis://localhost:6379

rabbitmq:
  uri: amqp://localhost:5672
